FROM python:3.5-alpine
ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && python /app/setup.py develop
CMD ["autolandweb"]
