FROM python:3.5-alpine

ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD dev-requirements.txt /dev-requirements.txt
RUN pip install -r /dev-requirements.txt

ADD . /app
WORKDIR /app

CMD ["python"]
