FROM python:3.5-alpine

ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
ADD test-requirements.txt /test-requirements.txt
RUN pip install -r /test-requirements.txt

# Create a Dockerflow version file at the root so
# we don't map over it below.
RUN echo '{\
    "source": "https://hg.mozilla.org/automation/conduit",\
    "version": "0.0.0",\
    "commit": "",\
    "build": ""\
}' >> /version.json

ADD . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && python /app/setup.py develop
CMD ["autolandweb"]
