# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  hgserver:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - data-volume:/repos
      - ./docker/hgweb.conf:/etc/hg/hgweb.conf
    environment:
      - HG_RELEASE=4.1
      - HG_WEB_CONF=/etc/hg/hgweb.conf
    depends_on:
      - hgrepoinit

  hgrepoinit:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    volumes:
      - data-volume:/repos
    environment:
      - HG_RELEASE=4.1
      - HG_WEB_CONF=/etc/hg/hgweb.conf
    entrypoint:
      - hg
      - init
      - /repos/testrepo

volumes:
  data-volume:
