# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile

  ## staginghgserver
  hgserver:
    build:
      context: ../staginghgserver
      dockerfile: ./docker/Dockerfile
    volumes:
      - data-volume:/repos
      - ../staginghgserver/extensions:/hgext
      - ../staginghgserver/docker/hgweb.conf:/etc/hg/hgweb.conf
    environment:
      - COMMIT_INDEX_URL=http://commitindex
    depends_on:
      - hgrepoinit

  hgrepoinit:
    build:
      context: ../staginghgserver
      dockerfile: ./docker/Dockerfile
    volumes:
      - data-volume:/repos
    entrypoint:
      - hg
      - init
      - /repos/testrepo

  ## commitindex
  commitindex:
    build:
      context: ../commitindex
      dockerfile: ./docker/commitindex/dockerfile-dev
    volumes:
      - ../commitindex:/app
    depends_on:
      - bmo
    environment:
      - PORT=80
      - DEBUG=1
      - BUGZILLA_URL=http://bmo

  mountebank:
    build:
      context: ../docker/mountebank/
    command: start --logfile /mb.log --debug --mock

  bmo:
    build:
      context: docker/bmo
      dockerfile: Dockerfile
    ports:
      - "7777:80"

volumes:
  data-volume:
