# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile
    volumes:
      - ..:/root/conduit:ro

  ## staginghgserver
  hgserver:
    build:
      context: ../staginghgserver
      dockerfile: ./docker/Dockerfile
    volumes:
      - data-volume:/repos
      - ../staginghgserver/extensions:/hgext
      - ../staginghgserver/docker/hgweb.conf:/etc/hg/hgweb.conf
    environment:
      - COMMIT_INDEX_URL=http://commitindex
    depends_on:
      - hgrepoinit

  hgrepoinit:
    build:
      context: ../staginghgserver
      dockerfile: ./docker/Dockerfile
    volumes:
      - data-volume:/repos
    entrypoint:
      - hg
      - init
      - /repos/testrepo

  # commitindex
  commitindex:
    build:
      context: ../commitindex
      dockerfile: ./docker/commitindex/dockerfile-dev
    volumes:
      - ../commitindex:/app
    depends_on:
      - bmo
    environment:
      - PORT=80
      - DEBUG=1
      - BUGZILLA_URL=http://bmo

  mountebank:
    build:
      context: ../docker/mountebank/
    command: start --logfile /mb.log --debug --mock

  bmo:
    build:
      context: docker/bmo
      dockerfile: Dockerfile
    ports:
      - "7777:80"

  phabricator:
    build:
      context: docker/phabricator
      dockerfile: Dockerfile
    volumes:
      - phabricator-www:/var/www/html
      - phabricator-local-repo:/repo
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.dev:7788/
    depends_on:
      - phabdb

  # Use '.dev' in the name so 'phabricator.dev' resolves to the correct
  # IP both inside and outside the docker-compose network.
  phabricator.dev:
    image: nginx:alpine
    ports:
      - "7788:80"
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
      - phabricator-www:/var/www/html:ro
    depends_on:
      - phabricator

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  data-volume:
  phabricator-www:
  phabricator-mysql-db:
  phabricator-local-repo:
