# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM node:7.7-alpine

WORKDIR /code

COPY conduit-preset.js /code
COPY package.json /code
COPY yarn.lock /code
RUN yarn --pure-lockfile

# Update $PATH so yarn can find scripts installed by dependencies
ENV PATH /code/node_modules/.bin:$PATH

EXPOSE 4000

ENTRYPOINT ["yarn"]
CMD ["--help"]
