# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  web:
    image: nginx:alpine
    ports:
      - "8888:80"
      - "9999:9999"
    volumes:
      - ./docker/web/nginx-conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - webapi

  yarn:
    build:
      context: ./ui
      dockerfile: ./Dockerfile-dev
    command: start
    volumes:
      - ./ui/src:/code/src
      - ./ui/build:/code/build
      - ./ui/test:/code/test

  mountebank:
    build:
      context: docker/mountebank/
    command: start --logfile /mb.log --debug --mock

  webapi:
    build:
      context: ./webapi
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./webapi:/app
    environment:
      - AUTOLANDWEB_DEBUG=1
      - AUTOLANDWEB_PORT=9090
      - AUTOLANDWEB_PRETTY_LOG=1
      - AUTOLANDWEB_VERSION_PATH=/version.json
      - AC_ALLOW_ORIGIN=*
    depends_on:
      - mountebank
